/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */
typedef unsigned long size_t;
typedef long __off_t;
typedef long __off64_t;
struct _IO_FILE;
struct _IO_FILE;
typedef struct _IO_FILE FILE;
typedef void _IO_lock_t;
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
typedef struct _IO_FILE _IO_FILE;
struct Grid {
   char NAME[101] ;
   int LEVEL ;
   int TYPE ;
   int ORIENT ;
   double ANGLE ;
   int ANGLE_UNIT ;
   double PSTEP ;
   double QSTEP ;
   int PQSTEP_UNIT ;
   double PX ;
   double PY ;
   double QX ;
   double QY ;
   int PQXY_UNIT ;
   double ROT_ANGLE ;
};
struct Port {
   int PORTNUM ;
   double AMP ;
   int AMP_UNIT ;
   double PSC ;
   int PSC_UNIT ;
   double PSH ;
   int PSH_UNIT ;
   double PPA ;
   int PPA_UNIT ;
   double PHEPOL ;
   int PHEPOL_UNIT ;
   int OMIT_POL ;
   struct Port *NEXT ;
};
struct Elem {
   int TYPE ;
   char NAME[101] ;
   int LEVEL ;
   int GEOMETRY ;
   double RADIUS ;
   int RADIUS_UNIT ;
   double PDIM ;
   double QDIM ;
   int PQDIM_UNIT ;
   int MODEL ;
   double EXP ;
   double ANGLEE ;
   double ANGLEH ;
   int ANGLE_UNIT ;
   double TAPERE ;
   double TAPERH ;
   int TAPER_UNIT ;
   int POLARIZATION ;
   double PHEPOL ;
   int PHEPOL_UNIT ;
   int DIRECTION ;
   double GAIN ;
   int GAIN_UNIT ;
   int NPORTS ;
   struct Port *PORT_PTR ;
};
struct Group;
struct Group;
struct PQExp {
   int dummy ;
};
struct GrAmpExc {
   int TYPE ;
   double UNIF_VAL ;
   double CENTRE ;
   double P1_ET ;
   double P2_ET ;
   double Q1_ET ;
   double Q2_ET ;
   int AMP_UNIT ;
   struct PQExp *PQEXP_PTR ;
};
struct GrPhaExc {
   int TYPE ;
   double UNIF_VAL ;
   double CENTRE ;
   double P1_EP ;
   double P2_EP ;
   double Q1_EP ;
   double Q2_EP ;
   int DIRECTION ;
   int OMIT_ANGLE ;
   double ANGLE_START ;
   double ANGLE_STEP ;
   int OMIT_PHASE ;
   double PHASE_START ;
   double PHASE_STEP ;
   double U ;
   double V ;
   double THETA ;
   double PHI ;
   struct PQExp *PQEXP_PTR ;
   int ANGLE_UNIT ;
   int PHASE_UNIT ;
};
struct Err {
   int AMP_TYPE ;
   double AMP_STDEV ;
   double AMP_LINOFFS ;
   double AMP_LINSTEP ;
   double AMP_2NDCENT ;
   double AMP_2NDPET ;
   double AMP_2NDQET ;
   int AMP_UNIT ;
   int PHASE_TYPE ;
   double PHASE_STDEV ;
   double PHASE_LINOFFS ;
   double PHASE_LINSTEP ;
   double PHASE_2NDCENT ;
   double PHASE_2NDPSID ;
   double PHASE_2NDQSID ;
   double PHASE_QUANTSTEP ;
   int PHASE_UNIT ;
};
struct Fail {
   int NUM_FAULTY_EL ;
   double FIXED_AMP ;
   double FIXED_PHASE ;
};
struct AddRem;
struct AddRem;
struct Geomnode;
struct Geomnode;
struct Group {
   char NAME[101] ;
   struct Grid *GRID_PTR ;
   struct Elem *ELEM_PTR ;
   struct AddRem *ADDREM_PTR ;
   struct GrAmpExc *GRAMPEXC_PTR ;
   struct GrPhaExc *GRPHAEXC_PTR ;
   struct Err *ERR_PTR ;
   struct Fail *FAIL_PTR ;
   struct Group *NEXT ;
   int NUM_OF_NODES ;
   int SHAPE ;
   double PSIZE ;
   double QSIZE ;
   struct Geomnode *GEOMNODE_PTR ;
   int BUILT ;
   struct Group *SUPER_GROUP_PTR[5] ;
};
struct Node;
struct Node;
struct AddRem {
   int ADDREM_TYPE ;
   int BLOCK_TYPE ;
   struct Node *NODE_PTR ;
   struct AddRem *NEXT ;
};
struct Node {
   int OMIT_ORIENT ;
   int PCOORD ;
   int QCOORD ;
   double THEA ;
   double PHEA ;
   double PSEA ;
   int ANGLE_UNIT ;
   struct Node *NEXT ;
};
struct charac {
   char info ;
   int LINE_NUM ;
   struct charac *PREV ;
   struct charac *NEXT ;
};
struct Geomport;
struct Geomport;
struct Geomnode {
   int LOC_P ;
   int LOC_Q ;
   double XA ;
   double YA ;
   double ZA ;
   double THEA ;
   double PHEA ;
   double PSEA ;
   struct Geomport *GEOMPORT_PTR ;
   struct Geomnode *NEXT ;
   struct Geomnode *SUBGROUP_PTR ;
   int SHAPE ;
   double PSIZE ;
   double QSIZE ;
};
struct Geomport {
   double AMP ;
   double PSH ;
   double PSC ;
   double PPA ;
   double PHEPOL ;
   struct Geomport *NEXT ;
};
#pragma merger("0","/tmp/cil-CA02UFd4.i","")
#pragma merger("0","/tmp/cil-fXpzBcE_.i","")
extern int _IO_getc(_IO_FILE *__fp ) ;
extern int fclose(FILE *__stream ) ;
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
extern int putchar(int __c ) ;
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2), __leaf__)) strcpy)(char * __restrict  __dest ,
                                                                                                 char const   * __restrict  __src ) ;
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2), __leaf__)) strcat)(char * __restrict  __dest ,
                                                                                                 char const   * __restrict  __src ) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) strcmp)(char const   *__s1 ,
                                                                                               char const   *__s2 )  __attribute__((__pure__)) ;
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1), __leaf__)) strlen)(char const   *__s )  __attribute__((__pure__)) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__nonnull__(1), __leaf__)) atof)(char const   *__nptr )  __attribute__((__pure__)) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) atoi)(char const   *__nptr )  __attribute__((__pure__)) ;
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
extern  __attribute__((__nothrow__)) unsigned short const   **( __attribute__((__leaf__)) __ctype_b_loc)(void)  __attribute__((__const__)) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) acos)(double __x ) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) asin)(double __x ) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) atan)(double __x ) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) cos)(double __x ) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) sin)(double __x ) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) pow)(double __x ,
                                                                             double __y ) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) sqrt)(double __x ) ;

char Keywords[126][21]  ;
char ErrorMessages[101][101]  ;
char MOSErrors[21][101]  ;
char GLOBLE_FILENAME[101]  ;
void parserro(struct charac *err_ptr , int errcode , char *s ) ;
void kwdsinit(void) ;
void emsginit(void) ;
void unaminit(void) ;
void moseinit(void) ;
void glvainit(void) ;
char TapeGet(struct charac **tp ) ;
void waitcont(void) ;
int isletter(char ch ) ;
int InKWords(char *WORD ) ;
int InUNames(char *WORD ) ;
void interror(char *subname ) ;
int InserUN(char *WORD ) ;
int EndOfTape(struct charac **p ) ;
void floatsup(void) ;
void nomefile(char *fn ) ;
void prnfile(struct charac *firstel ) ;
int answer(char *domanda ) ;
int readfil3(char *filename , struct charac **firstel , struct charac **lastel ) ;
int GetKeyword(char *kw , struct charac **tp ) ;
int GetUName(char *word , struct charac **tp ) ;
int GetReal(double *reale , struct charac **tp ) ;
int GetUReal(struct charac *p1 , struct charac **pp2 , double *ureal_ptr ) ;
int Get1Real(struct charac *p1 , struct charac **pp2 , double *ureal_ptr ) ;
int GetInt(struct charac *p1 , struct charac **pp2 , int *intero ) ;
int GetNatur(struct charac *p1 , struct charac **pp2 , int *natur_ptr ) ;
int lenunit(struct charac **tp , int *unit ) ;
int angunit(struct charac *p1 , struct charac **pp2 , int *angle_unit_ptr ) ;
int ampunit(struct charac **tp , int *unit_ptr ) ;
int squgrdef(struct charac *p1 , struct charac **pp2 , double *pstep_ptr , int *pstep_unit_ptr ) ;
int recgrdef(struct charac *p1 , struct charac **pp2 , double *pstep_ptr , double *qstep_ptr ,
             int *pqstep_unit_ptr ) ;
int hexgrdef(struct charac *p1 , struct charac **pp2 , double *pstep_ptr , int *pstep_unit_ptr ) ;
int trigrdef(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr ,
             double *pstep_ptr , double *qstep_ptr , int *pqstep_unit_ptr , double *px_ptr ,
             double *py_ptr , double *qx_ptr , double *qy_ptr , int *pqxy_unit_ptr ) ;
int griddef1(struct charac *p1 , struct charac **pp2 , struct Grid **grid_ptr ) ;
int doubstep(struct charac *p1 , struct charac **pp2 , double *pstep_ptr , double *qstep_ptr ,
             int *pqstep_unit_ptr ) ;
int angclaus(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr ) ;
int angstep(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr ,
            double *pstep_ptr , double *qstep_ptr , int *pqstep_unit_ptr ) ;
int versdef(struct charac *p1 , struct charac **pp2 , double *px_ptr , double *py_ptr ,
            double *qx_ptr , double *qy_ptr , int *pqxy_unit_ptr ) ;
int sinstep(struct charac *p1 , struct charac **pp2 , double *step_ptr , int *step_unit_ptr ) ;
int recspec(struct charac *p1 , struct charac **pp2 , double *pdim_ptr , double *qdim_ptr ,
            int *pqdim_unit_ptr ) ;
int geomspec(struct charac *p1 , struct charac **pp2 , int *geometry_ptr , double *radius_ptr ,
             int *radius_unit_ptr , double *pdim_ptr , double *qdim_ptr , int *pqdim_unit_ptr ) ;
int circspec(struct charac *p1 , struct charac **pp2 , double *radius_ptr , int *radius_unit_ptr ) ;
int extmod(struct charac *p1 , struct charac **pp2 ) ;
int gaussel(struct charac *p1 , struct charac **pp2 , double *anglee_ptr , double *angleh_ptr ,
            int *angle_unit_ptr , double *tapere_ptr , double *taperh_ptr , int *taper_unit_ptr ) ;
int cosinus(struct charac *p1 , struct charac **pp2 , double *exp_ptr ) ;
int modspec(struct charac *p1 , struct charac **pp2 , int *model_ptr , double *exp_ptr ,
            double *anglee_ptr , double *angleh_ptr , int *angle_unit_ptr , double *tapere_ptr ,
            double *taperh_ptr , int *taper_unit_ptr ) ;
int angval(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr ) ;
int polor(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr ) ;
int linpol(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr ) ;
int circpol(struct charac *p1 , struct charac **pp2 , int *direction_ptr ) ;
int polspec(struct charac *p1 , struct charac **pp2 , int *polarization_ptr , double *phepol_ptr ,
            int *phepol_unit_ptr , int *direction_ptr ) ;
int gainunit(struct charac *p1 , struct charac **pp2 , int *gain_unit_ptr ) ;
int gainval(struct charac *p1 , struct charac **pp2 , double *gain_ptr , int *gain_unit_ptr ) ;
int gainspec(struct charac *p1 , struct charac **pp2 , double *gain_ptr , int *gain_unit_ptr ) ;
int sinelem(struct charac *p1 , struct charac **pp2 , struct Elem **elem_ptr ) ;
int pshdef1(struct charac *p1 , struct charac **pp2 , double *psh_ptr , int *psh_unit_ptr ) ;
int pscdef1(struct charac *p1 , struct charac **pp2 , double *psc_ptr , int *psc_unit_ptr ) ;
int ppadef1(struct charac *p1 , struct charac **pp2 , double *ppa_ptr , int *ppa_unit_ptr ) ;
int polorbis(struct charac *p1 , struct charac **pp2 , double *phepol_ptr , int *phepol_unit_ptr ) ;
int ampval(struct charac *p1 , struct charac **pp2 , double *amp_ptr , int *amp_unit_ptr ) ;
int portamp(struct charac *p1 , struct charac **pp2 , double *amp_ptr , int *amp_unit_ptr ) ;
int portdef(struct charac *p1 , struct charac **pp2 , struct Port *PORT_PTR , int *portnum_ptr ) ;
int portspec(struct charac *p1 , struct charac **pp2 , int *nports_ptr , struct Port **port_ptr ) ;
int elemdef(struct charac *p1 , struct charac **pp2 , struct Elem **elem_ptr ) ;
int nodorien(struct charac *p1 , struct charac **pp2 , double *theta_ptr , double *phi_ptr ,
             double *psi_ptr , int *angle_unit_ptr ) ;
int nodecoor(struct charac *p1 , struct charac **pp2 , int *pcoord_ptr , int *qcoord_ptr ) ;
int nodedef(struct charac *p1 , struct charac **pp2 , struct Node **node_ptr ) ;
int blockdef(struct charac *p1 , struct charac **pp2 , struct Node **node_ptr ) ;
int adddef(struct charac *p1 , struct charac **pp2 , struct AddRem **addrem_ptr ) ;
int remdef(struct charac *p1 , struct charac **pp2 , struct AddRem **addrem_ptr ) ;
int adremdef(struct charac *p1 , struct charac **pp2 , struct AddRem **addrem_ptr ) ;
int grgeodef(struct charac *p1 , struct charac **pp2 , struct AddRem **addrem_ptr ) ;
int hexdef(struct charac *p1 , struct charac **pp2 , struct Node **node_ptr ) ;
int polydef(struct charac *p1 , struct charac **pp2 , struct Node **node_ptr ) ;
int greldef(struct charac *p1 , struct charac **pp2 , struct Grid **grid_ptr , struct Elem **elem_ptr ) ;
int secoramp(struct charac *p1 , struct charac **pp2 , double *centre_ptr , double *p1_et_ptr ,
             double *p2_et_ptr , double *q1_et_ptr , double *q2_et_ptr , int *amp_unit_ptr ) ;
int unifamp(struct charac *p1 , struct charac **pp2 , double *unif_val_ptr , int *amp_unit_ptr ) ;
int grampexc(struct charac *p1 , struct charac **pp2 , struct GrAmpExc **grampexc_ptr ) ;
int angledir(struct charac *p1 , struct charac **pp2 , double *theta_ptr , double *phi_ptr ,
             int *angle_unit_ptr ) ;
int uvval(struct charac *p1 , struct charac **pp2 , double *val_ptr ) ;
int uvdir(struct charac *p1 , struct charac **pp2 , double *u_ptr , double *v_ptr ) ;
int beampha(struct charac *p1 , struct charac **pp2 , double *u_ptr , double *v_ptr ,
            double *theta_ptr , double *phi_ptr , int *angle_unit_ptr ) ;
int phaserot(struct charac *p1 , struct charac **pp2 , double *phase_start_ptr , double *phase_step_ptr ,
             int *phase_unit_ptr ) ;
int anglerot(struct charac *p1 , struct charac **pp2 , double *angle_start_ptr , double *angle_step_ptr ,
             int *angle_unit_ptr ) ;
int serotdir(struct charac *p1 , struct charac **pp2 , int *direction_ptr ) ;
int serotpar(struct charac *p1 , struct charac **pp2 , double *angle_start_ptr , double *angle_step_ptr ,
             int *omit_phase_ptr , double *phase_start_ptr , double *phase_step_ptr ,
             int *angle_unit_ptr , int *phase_unit_ptr ) ;
int serotpha(struct charac *p1 , struct charac **pp2 , int *direction_ptr , int *omit_angle_ptr ,
             double *angle_start_ptr , double *angle_step_ptr , int *omit_phase_ptr ,
             double *phase_start_ptr , double *phase_step_ptr , int *angle_unit_ptr ,
             int *phase_unit_ptr ) ;
int secorpha(struct charac *p1 , struct charac **pp2 , double *centre_ptr , double *p1_ep_ptr ,
             double *p2_ep_ptr , double *q1_ep_ptr , double *q2_ep_ptr , int *phase_unit_ptr ) ;
int unifpha(struct charac *p1 , struct charac **pp2 , double *unif_val_ptr , int *phase_unit_ptr ) ;
int grphaexc(struct charac *p1 , struct charac **pp2 , struct GrPhaExc **grphaexc_ptr ) ;
int grexcdef(struct charac *p1 , struct charac **pp2 , struct GrAmpExc **grampexc_ptr ,
             struct GrPhaExc **grphaexc_ptr ) ;
int groupdef(struct charac *p1 , struct charac **pp2 , struct Group **group_ptr ) ;
int intmin(int a , int b ) ;
int intmax(int a , int b ) ;
double doubmin(double a , double b ) ;
double doubmax(double a , double b ) ;
double dcos(double x ) ;
double dsin(double x ) ;
double dacos(double x ) ;
double dasin(double x ) ;
double datan(double x ) ;
int mmconv(double *x_ptr , int unit ) ;
int degconv(double *x_ptr , int unit ) ;
int linconv(double *x_ptr , int unit ) ;
int grwrite(struct Group *group_ptr , char *filename ) ;
int mksnode(struct AddRem *addrem_ptr , struct Geomnode **first_node_ptr , struct Geomnode **last_node_ptr ,
            double pstep , double qstep , double angle , int *nodes_num_ptr , int elem_shape ,
            double elem_pdim , double elem_qdim ) ;
int mksblock(struct AddRem *addrem_ptr , struct Geomnode **first_node_ptr , struct Geomnode **last_node_ptr ,
             double pstep , double qstep , double angle , int *nodes_num_ptr , int elem_shape ,
             double elem_pdim , double elem_qdim ) ;
int mkshex(struct AddRem *addrem_ptr , struct Geomnode **first_node_ptr , struct Geomnode **last_node_ptr ,
           double pstep , double qstep , double angle , int *nodes_num_ptr , int elem_shape ,
           double elem_pdim , double elem_qdim ) ;
int addscan(struct Group *group_ptr ) ;
int extremes(struct Geomnode *gnode_ptr , int *pnum_ptr , int *qnum_ptr ) ;
int simgroup(struct Group *group_ptr ) ;
int fixnodor(struct Node *node_ptr ) ;
int fixsgrel(struct Group *group_ptr ) ;
int fixsgrid(struct Grid *grid ) ;
int fixselem(struct Elem *elem_ptr ) ;
int extsize(struct Geomnode *gnode_ptr , double elem_pdim , double elem_qdim , double *xsize_ptr ,
            double *ysize_ptr ) ;
int sgrrot(struct Geomnode *start_ptr , double XC , double YC , double phi ) ;
int fixgramp(struct GrAmpExc *g ) ;
int fixport(struct Elem *elem_ptr ) ;
int sgrampun(struct GrAmpExc *grampexc_ptr , struct Geomnode *geomnode_ptr , struct Port *port_ptr ) ;
int simamp(struct Group *group_ptr ) ;
int pqlimits(struct Geomnode *gnode_ptr , struct Geomnode **pmin_ptr , struct Geomnode **pmax_ptr ,
             struct Geomnode **qmin_ptr , struct Geomnode **qmax_ptr ) ;
int sgramp2n(struct GrAmpExc *grampexc_ptr , struct Geomnode *geomnode_ptr , struct Port *port_ptr ,
             int group_shape ) ;
double secorder(double a , double b , double c , double d , double e , double x ,
                double y ) ;
int simpol(struct Group *group_ptr ) ;
int simpha(struct Group *group_ptr ) ;
int fixgrpha(struct GrPhaExc *g ) ;
int sgrphaun(struct GrPhaExc *grphaexc_ptr , struct Geomnode *geomnode_ptr , struct Port *port_ptr ) ;
int sgrpha2n(struct GrPhaExc *grphaexc_ptr , struct Geomnode *geomnode_ptr , struct Port *port_ptr ,
             int group_shape ) ;
int gnodfind(struct Geomnode *gnode_list_start_ptr , struct Geomnode **gnode_ptr ,
             int p , int q ) ;
void gnodevis(int p , int q , double angle , double phase , struct Geomnode *gnode_list_start_ptr ) ;
void seqrotrg(double angle_start , double angle_step , double phase_start , double phase_step ,
              struct Geomnode *g ) ;
void seqrothg(double angle_start , double angle_step , double phase_start , double phase_step ,
              struct Geomnode *g ) ;
int sgrphasr(struct Group *group_ptr ) ;
int main(int argc , char **argv )
{
  struct charac *first ;
  struct charac *last ;
  struct charac *cp ;
  struct Group *group_ptr ;
  int error ;
  char fn[101] ;
  int tmp ;
  {












  {
  strcpy((char * __restrict  )(GLOBLE_FILENAME), (char const   * __restrict  )*(argv + 1));
  glvainit();
  nomefile(fn);
  tmp = readfil3(fn, & first, & last);
  }





  {
  prnfile(first);
  error = groupdef(first, & cp, & group_ptr);

  }
  if (error != 0) {

    exit(1);

  }
  {
  error = simgroup(group_ptr);
  }





  {
  error = simamp(group_ptr);
  }





  {
  error = simpha(group_ptr);
  }
  if (error) {

    exit(1);

  }
  {
  simpol(group_ptr);


  grwrite(group_ptr, fn);
  }
  return (0);
}
}
int adddef(struct charac *p1 , struct charac **pp2 , struct AddRem **addrem_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  struct Node *no_ptr ;
  struct Node **node_ptr ;
  void *tmp ;
  void *tmp___0 ;
  void *tmp___1 ;
  void *tmp___2 ;
  {
  {


  node_ptr = & no_ptr;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[79], curr_ptr);
  }
  if (error != 0) {

    return (1);
  }
  {
  error = nodedef(*curr_ptr, curr_ptr, node_ptr);
  }







  if (error == 0) {
    {
    tmp = malloc(sizeof(struct AddRem ));
    *addrem_ptr = (struct AddRem *)tmp;
    }










    *pp2 = *curr_ptr;
    return (0);
  }
  {
  error = blockdef(*curr_ptr, curr_ptr, node_ptr);
  }







  if (error == 0) {
    {
    tmp___0 = malloc(sizeof(struct AddRem ));
    *addrem_ptr = (struct AddRem *)tmp___0;
    }







    (*addrem_ptr)->BLOCK_TYPE = 1;
    (*addrem_ptr)->NODE_PTR = *node_ptr;

    *pp2 = *curr_ptr;
    return (0);
  }




























  {
  error = hexdef(*curr_ptr, curr_ptr, node_ptr);
  }







                  {
    {
    tmp___2 = malloc(sizeof(struct AddRem ));
    *addrem_ptr = (struct AddRem *)tmp___2;
    }








    (*addrem_ptr)->NODE_PTR = *node_ptr;

    *pp2 = *curr_ptr;

  }






}
}
int addscan(struct Group *group_ptr )
{
  struct AddRem *add_ptr ;
  struct Geomnode *ap1_ptr ;
  struct Geomnode **app1_ptr ;
  struct Geomnode *ap2_ptr ;
  struct Geomnode **app2_ptr ;
  struct Geomnode *primo_ptr ;
  struct Geomnode *ultimo_ptr ;
  int new_nodes ;
  int *new_nodes_ptr ;
  int pnum ;
  int *pnum_ptr ;
  int qnum ;
  int *qnum_ptr ;
  int elem_shape ;
  double elem_pdim ;
  double elem_qdim ;
  double pstep ;
  double qstep ;
  double angle ;
  double rot_angle ;
  int nodes_num ;
  int group_shape ;
  double group_psize ;
  double group_qsize ;
  double *group_psize_ptr ;
  double *group_qsize_ptr ;
  {


  app1_ptr = & ap1_ptr;

  app2_ptr = & ap2_ptr;



  new_nodes_ptr = & new_nodes;






  pstep = (group_ptr->GRID_PTR)->PSTEP;
  qstep = (group_ptr->GRID_PTR)->QSTEP;
  angle = (group_ptr->GRID_PTR)->ANGLE;

  elem_pdim = (group_ptr->ELEM_PTR)->PDIM;
  elem_qdim = (group_ptr->ELEM_PTR)->QDIM;


         {
    elem_shape = 2;
  }
  add_ptr = group_ptr->ADDREM_PTR;


  {
  while (1) {

    if (! ((unsigned long )add_ptr != (unsigned long )((void *)0))) {
      goto while_break;
    }





    {



    if (add_ptr->BLOCK_TYPE == 1) {
      goto case_1;
    }



                                  {
      goto case_3;
    }
















    case_1: /* CIL Label */
    {
    mksblock(add_ptr, app1_ptr, app2_ptr, pstep, qstep, angle, new_nodes_ptr, elem_shape,
             elem_pdim, elem_qdim);
    }









    goto switch_break;





    case_3: /* CIL Label */
                         {




    }
    {
    mkshex(add_ptr, app1_ptr, app2_ptr, pstep, qstep, angle, new_nodes_ptr, elem_shape,
           elem_pdim, elem_qdim);
    }










    switch_break: /* CIL Label */ ;
    }
    nodes_num += *new_nodes_ptr;
    if ((unsigned long )primo_ptr == (unsigned long )((void *)0)) {
      primo_ptr = *app1_ptr;
    } else {
      ultimo_ptr->NEXT = *app1_ptr;
    }
    ultimo_ptr = *app2_ptr;

    add_ptr = add_ptr->NEXT;
  }
  while_break: /* CIL Label */ ;
  }






















  group_ptr->NUM_OF_NODES = nodes_num;




  group_ptr->GEOMNODE_PTR = primo_ptr;
  return (0);
}
}
int adremdef(struct charac *p1 , struct charac **pp2 , struct AddRem **addrem_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {

  *curr_ptr = p1;


  error = adddef(*curr_ptr, curr_ptr, addrem_ptr);
  }
  if (error == 0) {
    *pp2 = *curr_ptr;
    return (0);
  }





















                  {
    return (1);
  }

}
}






































int ampval(struct charac *p1 , struct charac **pp2 , double *amp_ptr , int *amp_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetReal(amp_ptr, curr_ptr);
  }









  *pp2 = *curr_ptr;
  return (0);
}
}
















































































































































































int angunit(struct charac *p1 , struct charac **pp2 , int *angle_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int tmp ;
  int tmp___0 ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;


  }


         {

    tmp = GetKeyword(Keywords[52], curr_ptr);






  }
  *pp2 = *curr_ptr;


}
}
int angval(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetReal(angle_ptr, curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = angunit(*curr_ptr, curr_ptr, angle_unit_ptr);
  }



  *pp2 = *curr_ptr;


}
}
extern int gets() ;

































































int blockdef(struct charac *p1 , struct charac **pp2 , struct Node **node_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  int pcoord ;
  int *pcoord_ptr ;
  int qcoord ;
  int *qcoord_ptr ;
  struct Node *primo_ptr ;
  struct Node *ultimo_ptr ;
  struct Node *app_ptr ;
  void *tmp ;
  void *tmp___0 ;
  {
  {

  pcoord_ptr = & pcoord;
  qcoord_ptr = & qcoord;



  *curr_ptr = p1;


  error = GetKeyword(Keywords[76], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = nodecoor(*curr_ptr, curr_ptr, pcoord_ptr, qcoord_ptr);
  }












  {
  tmp = malloc(sizeof(struct Node ));
  app_ptr = (struct Node *)tmp;
  }







  {
  app_ptr->PCOORD = pcoord;
  app_ptr->QCOORD = qcoord;





  primo_ptr = app_ptr;
  ultimo_ptr = app_ptr;
  error = nodecoor(*curr_ptr, curr_ptr, pcoord_ptr, qcoord_ptr);
  }












  {
  tmp___0 = malloc(sizeof(struct Node ));
  app_ptr = (struct Node *)tmp___0;
  }







  app_ptr->PCOORD = pcoord;
  app_ptr->QCOORD = qcoord;





  ultimo_ptr->NEXT = app_ptr;


  *node_ptr = primo_ptr;
  *pp2 = *curr_ptr;
  return (0);
}
}
int circpol(struct charac *p1 , struct charac **pp2 , int *direction_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {


  *curr_ptr = p1;

  error = GetKeyword(Keywords[38], curr_ptr);
  }



  {
  error = GetKeyword(Keywords[65], curr_ptr);
  }














  *pp2 = *curr_ptr;
  return (0);
}
}
int circspec(struct charac *p1 , struct charac **pp2 , double *radius_ptr , int *radius_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {


  *curr_ptr = p1;
  error = GetKeyword(Keywords[38], curr_ptr);
  }



  {
  error = GetKeyword(Keywords[5], curr_ptr);

  error = Get1Real(*curr_ptr, curr_ptr, radius_ptr);
  }












  *pp2 = *curr_ptr;
  return (0);
}
}



























































double dcos(double x )
{
  double tmp ;
  {
  {
  tmp = cos((x * 3.141592654) / (double )180);
  }
  return (tmp);
}
}



































































































double dsin(double x )
{
  double tmp ;
  {
  {
  tmp = sin((x * 3.141592654) / (double )180);
  }
  return (tmp);
}
}
int elemdef(struct charac *p1 , struct charac **pp2 , struct Elem **elem_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  char name[101] ;
  void *tmp ;
  {
  {

  *curr_ptr = p1;

  tmp = malloc(sizeof(struct Elem ));
  *elem_ptr = (struct Elem *)tmp;
  }






  {
  error = GetKeyword(Keywords[28], curr_ptr);
  }















  {
  error = sinelem(*curr_ptr, curr_ptr, elem_ptr);
  }
  if (error == 0) {


    return (0);
  }
  return (17);
}
}
void emsginit(void)
{
  int i ;
  {














  strcpy((char * __restrict  )(ErrorMessages[1]), (char const   * __restrict  )"** ERROR 1: Keyword expected: ");






















  strcpy((char * __restrict  )(ErrorMessages[24]), (char const   * __restrict  )"** ERROR 24: Incorrect ELEMENT definition.");





















  strcpy((char * __restrict  )(ErrorMessages[46]), (char const   * __restrict  )"** ERROR 46: Too few PORT definitions.");


  strcpy((char * __restrict  )(ErrorMessages[49]), (char const   * __restrict  )"** ERROR 49: Incorrect element PORTS definition.");


















  strcpy((char * __restrict  )(ErrorMessages[68]), (char const   * __restrict  )"** ERROR 68: Missing SECOND ORDER parameter(s).");







  strcpy((char * __restrict  )(ErrorMessages[76]), (char const   * __restrict  )"** ERROR 76: Incorrect SECOND ORDER phase definition.");
  strcpy((char * __restrict  )(ErrorMessages[77]), (char const   * __restrict  )"** ERROR 77: Incorrect ROTATION SEQUENTIAL phase definition.");


  strcpy((char * __restrict  )(ErrorMessages[80]), (char const   * __restrict  )"** ERROR 80: Incorrect PHASE excitation definition.");

  strcpy((char * __restrict  )(ErrorMessages[82]), (char const   * __restrict  )"** ERROR 82: Incorrect GROUP definition, group: ");











  strcpy((char * __restrict  )(ErrorMessages[94]), (char const   * __restrict  )"** ERROR 94: At least one ADD statement is required.");







}
}

















































































































































































































































































































































int fixselem(struct Elem *elem_ptr )
{
  double radius ;
  double *radius_ptr ;
  int radius_unit ;
  double pdim ;
  double *pdim_ptr ;
  double qdim ;
  double *qdim_ptr ;
  int pqdim_unit ;
  struct Port *port_ptr ;
  void *tmp ;
  {




  radius = elem_ptr->RADIUS;

  pdim = elem_ptr->PDIM;
  qdim = elem_ptr->QDIM;

  {
  if (elem_ptr->GEOMETRY == 0) {
    goto case_0;
  }
                               {
    goto case_1;
  }

  case_0: /* CIL Label */
  {


  radius = sqrt(pdim * pdim + qdim * qdim);
  }

  case_1: /* CIL Label */
  {

  pdim = (double )2 * radius;
  qdim = (double )2 * radius;
  }






  }


                             {
    {
    tmp = malloc(sizeof(struct Port ));
    port_ptr = (struct Port *)tmp;
    }







    port_ptr->AMP = (double )1;







    port_ptr->PHEPOL = (double )90;



    elem_ptr->NPORTS = 1;
    elem_ptr->PORT_PTR = port_ptr;
  }
  {

  elem_ptr->RADIUS = radius;

  elem_ptr->PDIM = pdim;



  }
  return (0);
}
}
int fixsgrel(struct Group *group_ptr )
{
  struct Grid *grid ;
  struct Elem *elem ;
  double pstep ;
  double qstep ;
  double angle ;
  double rot_angle ;
  double radius ;
  double pdim ;
  double qdim ;
  double px ;
  double py ;
  double qx ;
  double qy ;
  double tmp ;
  double tmp___0 ;
  double tmp___1 ;
  double tmp___2 ;
  {
  {
  grid = group_ptr->GRID_PTR;
  elem = group_ptr->ELEM_PTR;
  fixselem(elem);
  fixsgrid(grid);

  }
  {
  if (grid->TYPE == 0) {
    goto case_0;
  }
  if (grid->TYPE == 1) {
    goto case_1;
  }
                       {
    goto case_2;
  }




  case_0: /* CIL Label */










         { //Added block












      printf((char const   * __restrict  )"\n%s%s", MOSErrors[2], group_ptr->NAME);



  }

  goto switch_break;
  case_1: /* CIL Label */
                                 {
    if ((group_ptr->GRPHAEXC_PTR)->TYPE == 3) {
      grid->PSTEP = elem->RADIUS;
      grid->QSTEP = elem->RADIUS;
    } else {
      grid->PSTEP = elem->PDIM;

    }
  }





















  goto switch_break;
  case_2: /* CIL Label */
                           {




  }
                                 {
    grid->PSTEP = elem->PDIM;

  }




























































































































































































































  switch_break: /* CIL Label */ ;
  }
  {
  printf((char const   * __restrict  )"\n** Generating GROUP: %s.", group_ptr->NAME);
  printf((char const   * __restrict  )"\n** PSTEP,QSTEP set to:%f,%f", grid->PSTEP,
         grid->QSTEP);
  printf((char const   * __restrict  )"\n** Grid ANGLE set to:%f ", grid->ANGLE);
  printf((char const   * __restrict  )"\n** Group ROT_ANGLE set to: %f \n", grid->ROT_ANGLE);
  }
  return (0);
}
}
int fixsgrid(struct Grid *grid )
{
  double angle ;
  double *angle_ptr ;
  int angle_unit ;
  double pstep ;
  double *pstep_ptr ;
  double qstep ;
  double *qstep_ptr ;
  int pqstep_unit ;
  double px ;
  double *px_ptr ;
  double py ;
  double *py_ptr ;
  double qx ;
  double *qx_ptr ;
  double qy ;
  double *qy_ptr ;
  int pqxy_unit ;
  double rot_angle ;
  {









  pstep = grid->PSTEP;








  {



  if (grid->TYPE == 0) {
    goto case_0;
  }
  if (grid->TYPE == 1) {
    goto case_1;
  }
                       {
    goto case_2;
  }









  case_0: /* CIL Label */
                           {


    qstep = pstep;

  }




  case_1: /* CIL Label */
                           {




  }


  angle = (double )90;
  goto switch_break;
  case_2: /* CIL Label */
                           {




  }


  angle = (double )60;

































  switch_break: /* CIL Label */ ;
  }



  rot_angle = (double )0;
  grid->ANGLE = angle;


  grid->QSTEP = qstep;







  grid->ROT_ANGLE = rot_angle;
  return (0);
}
}
void floatsup(void)
{
  double dummy ;
  {

  dummy = 1.0 + 0.0;
  printf((char const   * __restrict  )"*******************************************************************************\n");
  printf((char const   * __restrict  )"                         ARRAY PREPROCESSOR ver. %3.1f\n",
         dummy);
  printf((char const   * __restrict  )"*******************************************************************************\n");


}
}



































































































































































int geomspec(struct charac *p1 , struct charac **pp2 , int *geometry_ptr , double *radius_ptr ,
             int *radius_unit_ptr , double *pdim_ptr , double *qdim_ptr , int *pqdim_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[29], curr_ptr);
  }






  {
  *geometry_ptr = 0;
  error = recspec(*curr_ptr, curr_ptr, pdim_ptr, qdim_ptr, pqdim_unit_ptr);
  }
  if (error == 0) {
    *pp2 = *curr_ptr;
    return (0);
  }






  {
  *geometry_ptr = 1;
  error = circspec(*curr_ptr, curr_ptr, radius_ptr, radius_unit_ptr);
  }
                  {
    *pp2 = *curr_ptr;

  }








}
}
int Get1Real(struct charac *p1 , struct charac **pp2 , double *ureal_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {

  *curr_ptr = p1;
  error = GetReal(ureal_ptr, curr_ptr);
  }







  *pp2 = *curr_ptr;
  return (0);
}
}
int GetInt(struct charac *p1 , struct charac **pp2 , int *intero )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int i ;
  char num[6] ;
  char ch ;
  unsigned short const   **tmp ;
  unsigned short const   **tmp___0 ;
  {
  {
  curr_ptr = & curr;
  i = 0;
  *curr_ptr = p1;
  ch = TapeGet(curr_ptr);

  }







  {
  num[i] = ch;
  i ++;
  ch = TapeGet(curr_ptr);
  }
  {
  while (1) {
                                     ;
    {
    tmp___0 = __ctype_b_loc();
    }
    if ((int const   )*(*tmp___0 + (int )ch) & 2048) {



    } else {
      goto while_break;
    }
               {
      num[i] = ch;
    }
    {
    i ++;
    ch = TapeGet(curr_ptr);
    }
  }
  while_break: /* CIL Label */ ;
  }






         {

    num[i] = (char )'\000';
  }
  {
  *intero = atoi((char const   *)(num));
  *pp2 = *curr_ptr;
  }
  return (0);
}
}
int GetKeyword(char *kw , struct charac **tp )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  char word[21] ;
  char ch ;
  int i ;
  unsigned short const   **tmp ;
  int tmp___0 ;
  {
  {
  i = 0;
  curr_ptr = & curr;
  *curr_ptr = *tp;
  ch = TapeGet(curr_ptr);
  }
  {
  while (1) {
                                     ;
    {
    tmp = __ctype_b_loc();
    }
    if ((int const   )*(*tmp + (int )ch) & 8) {

    } else { //Added block
    if ((int )ch == 95) {









    } else {
      goto while_break;
    }
    }
    {
    word[i] = ch;
    i ++;
    ch = TapeGet(curr_ptr);
    }
  }
  while_break: /* CIL Label */ ;
  }
  {
  word[i] = (char )'\000';
  tmp___0 = strcmp((char const   *)kw, (char const   *)(word));
  }
  if (tmp___0 == 0) {
    *tp = *curr_ptr;
    return (0);
  } else {
    return (1);
  }
}
}
int GetNatur(struct charac *p1 , struct charac **pp2 , int *natur_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  int val ;
  int *val_ptr ;
  {
  {

  val_ptr = & val;
  *curr_ptr = p1;
  error = GetInt(*curr_ptr, curr_ptr, val_ptr);
  }










  *natur_ptr = *val_ptr;
  *pp2 = *curr_ptr;
  return (0);
}
}
int GetReal(double *reale , struct charac **tp )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int i ;
  char num[101] ;
  char ch ;
  unsigned short const   **tmp ;
  unsigned short const   **tmp___0 ;
  {
  {
  curr_ptr = & curr;
  i = 0;
  *curr_ptr = *tp;
  ch = TapeGet(curr_ptr);
  tmp = __ctype_b_loc();
  }
  if (((int const   )*(*tmp + (int )ch) & 2048) == 0) {

      if ((int )ch != 45) {

          return (13);

      }

  }





  {
  while (1) {
                                     ;
    {
    tmp___0 = __ctype_b_loc();
    }
    if ((int const   )*(*tmp___0 + (int )ch) & 2048) {

    } else { //Added block
    if ((int )ch == 46) {

    } else { //Added block


              //Added block


              //Added block
    if ((int )ch == 45) {




    } else {
      goto while_break;
    }


    }
    }
                 {
      num[i] = ch;
    }
    {
    i ++;
    ch = TapeGet(curr_ptr);
    }
  }
  while_break: /* CIL Label */ ;
  }





  {
  *reale = atof((char const   *)(num));
  *tp = *curr_ptr;
  }


}
}
int GetUName(char *word , struct charac **tp )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  char ch ;
  int i ;
  int tmp ;
  unsigned short const   **tmp___0 ;
  size_t tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  {
  {


  *curr_ptr = *tp;
  ch = TapeGet(curr_ptr);
  }
  {
  while (1) {
                                     ;
    {
    tmp = isletter(ch);
    }
    if (tmp) {

    } else {









        goto while_break;

    }
                 {
      *(word + i) = ch;
    }
    {
    i ++;
    ch = TapeGet(curr_ptr);
    }
  }
  while_break: /* CIL Label */ ;
  }






















  {
  tmp___3 = InKWords(word);
  }
  if (tmp___3 == 1) {
    return (6);
  }
  *tp = *curr_ptr;


}
}
int GetUReal(struct charac *p1 , struct charac **pp2 , double *ureal_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  double val ;
  double *val_ptr ;
  {
  {

  val_ptr = & val;
  *curr_ptr = p1;
  error = GetReal(val_ptr, curr_ptr);
  }







  *ureal_ptr = *val_ptr;
  *pp2 = *curr_ptr;
  return (0);
}
}
void glvainit(void)
{
  floatsup();
  kwdsinit();
  emsginit();

  moseinit();



}

























































int grampexc(struct charac *p1 , struct charac **pp2 , struct GrAmpExc **grampexc_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  double unif_val ;
  double *unif_val_ptr ;
  double centre ;
  double *centre_ptr ;
  double p1_et ;
  double *p1_et_ptr ;
  double p2_et ;
  double *p2_et_ptr ;
  double q1_et ;
  double *q1_et_ptr ;
  double q2_et ;
  double *q2_et_ptr ;
  int amp_unit ;
  int *amp_unit_ptr ;
  void *tmp ;
  void *tmp___0 ;
  {
  {

  unif_val_ptr = & unif_val;





  amp_unit_ptr = & amp_unit;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[42], curr_ptr);
  }




  {
  error = unifamp(*curr_ptr, curr_ptr, unif_val_ptr, amp_unit_ptr);
  }
                  {
    {
    tmp = malloc(sizeof(struct GrAmpExc ));
    *grampexc_ptr = (struct GrAmpExc *)tmp;
    }







    (*grampexc_ptr)->UNIF_VAL = unif_val;


    *pp2 = *curr_ptr;
    return (0);
  }




































}
}
int greldef(struct charac *p1 , struct charac **pp2 , struct Grid **grid_ptr , struct Elem **elem_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;



  error = griddef1(*curr_ptr, curr_ptr, grid_ptr);
  }









  {
  error = elemdef(*curr_ptr, curr_ptr, elem_ptr);
  }






  if (error == 17) {
    {
    printf((char const   * __restrict  )"\n%s", ErrorMessages[24]);
    }
    return (17);
  }
  *pp2 = *curr_ptr;


}
}
int grexcdef(struct charac *p1 , struct charac **pp2 , struct GrAmpExc **grampexc_ptr ,
             struct GrPhaExc **grphaexc_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;



  error = GetKeyword(Keywords[101], curr_ptr);
  }



  {
  error = grampexc(*curr_ptr, curr_ptr, grampexc_ptr);
  }






  {
  error = grphaexc(*curr_ptr, curr_ptr, grphaexc_ptr);
  }
  if (error != 0) {
    {
    printf((char const   * __restrict  )"\n%s", ErrorMessages[80]);
    }
    return (17);
  }



}
}
int grgeodef(struct charac *p1 , struct charac **pp2 , struct AddRem **addrem_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  struct AddRem *ultimo_ptr ;
  struct AddRem *a_ptr ;
  struct AddRem **app_ptr ;
  {
  {
  curr_ptr = & curr;


  app_ptr = & a_ptr;
  *curr_ptr = p1;


  error = adddef(*curr_ptr, curr_ptr, addrem_ptr);
  }
  if (error == 1) {
    {
    parserro(*curr_ptr, 94, (char *)" ");
    }
    return (17);
  }







  ultimo_ptr = *addrem_ptr;
  {
  while (1) {
                                     ;
    {
    error = adremdef(*curr_ptr, curr_ptr, app_ptr);
    }
    if (error == 1) {

      *pp2 = *curr_ptr;
      return (0);
    }







    ultimo_ptr->NEXT = *app_ptr;
    ultimo_ptr = *app_ptr;

  }
                                ;

  }
}
}
int griddef1(struct charac *p1 , struct charac **pp2 , struct Grid **grid_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int grid_type ;
  int orient ;
  int *orient_ptr ;
  double pstep ;
  double *pstep_ptr ;
  double qstep ;
  double *qstep_ptr ;
  int pqstep_unit ;
  int *pqstep_unit_ptr ;
  double angle ;
  double *angle_ptr ;
  int angle_unit ;
  int *angle_unit_ptr ;
  double px ;
  double *px_ptr ;
  double py ;
  double *py_ptr ;
  double qx ;
  double *qx_ptr ;
  double qy ;
  double *qy_ptr ;
  int pqxy_unit ;
  int *pqxy_unit_ptr ;
  int error ;
  void *tmp ;
  {
  {
  curr_ptr = & curr;

  pstep_ptr = & pstep;
  qstep_ptr = & qstep;
  pqstep_unit_ptr = & pqstep_unit;
  angle_ptr = & angle;
  angle_unit_ptr = & angle_unit;
  px_ptr = & px;
  py_ptr = & py;
  qx_ptr = & qx;
  qy_ptr = & qy;
  pqxy_unit_ptr = & pqxy_unit;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[14], curr_ptr);
  }




  {

  error = squgrdef(*curr_ptr, curr_ptr, pstep_ptr, pqstep_unit_ptr);
  }







  if (error != 0) {

    grid_type = 1;
    error = recgrdef(*curr_ptr, curr_ptr, pstep_ptr, qstep_ptr, pqstep_unit_ptr);








  }
  if (error != 0) {

    grid_type = 2;
    error = hexgrdef(*curr_ptr, curr_ptr, pstep_ptr, pqstep_unit_ptr);








  }
  if (error != 0) {
    {

    error = trigrdef(*curr_ptr, curr_ptr, angle_ptr, angle_unit_ptr, pstep_ptr, qstep_ptr,
                     pqstep_unit_ptr, px_ptr, py_ptr, qx_ptr, qy_ptr, pqxy_unit_ptr);
    }
                     {




      return (17);
    }
  }







  {
  tmp = malloc(sizeof(struct Grid ));
  *grid_ptr = (struct Grid *)tmp;
  }






  (*grid_ptr)->TYPE = grid_type;

  (*grid_ptr)->PSTEP = pstep;









  *pp2 = *curr_ptr;


}
}
int groupdef(struct charac *p1 , struct charac **pp2 , struct Group **group_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  char groupname[101] ;
  struct Grid *grid ;
  struct Grid **grid_ptr ;
  struct Elem *elem ;
  struct Elem **elem_ptr ;
  struct AddRem *addrem ;
  struct AddRem **addrem_ptr ;
  struct GrAmpExc *grampexc___0 ;
  struct GrAmpExc **grampexc_ptr ;
  struct GrPhaExc *grphaexc___0 ;
  struct GrPhaExc **grphaexc_ptr ;
  struct Err *err ;
  struct Err **err_ptr ;
  struct Fail *fail ;
  struct Fail **fail_ptr ;
  int tmp ;
  int tmp___0 ;
  void *tmp___1 ;
  {
  {
  curr_ptr = & curr;

  grid_ptr = & grid;

  elem_ptr = & elem;

  addrem_ptr = & addrem;

  grampexc_ptr = & grampexc___0;

  grphaexc_ptr = & grphaexc___0;




  *curr_ptr = p1;

  error = GetKeyword(Keywords[47], curr_ptr);
  }




  {
  tmp = GetUName(groupname, curr_ptr);
  }















  {

  error = greldef(*curr_ptr, curr_ptr, grid_ptr, elem_ptr);
  }
  if (error == 17) {
    return (17);
  }







  {
  error = grgeodef(*curr_ptr, curr_ptr, addrem_ptr);
  }
  if (error != 0) {
    {
    parserro(*curr_ptr, 82, groupname);
    }
    return (17);
  }
  {
  error = grexcdef(*curr_ptr, curr_ptr, grampexc_ptr, grphaexc_ptr);
  }
  if (error != 0) {
    {
    parserro(*curr_ptr, 82, (char *)" ");
    }
    return (17);
  }









  {
  tmp___1 = malloc(sizeof(struct Group ));
  *group_ptr = (struct Group *)tmp___1;
  }






  {
  strcpy((char * __restrict  )((*group_ptr)->NAME), (char const   * __restrict  )(groupname));




  (*group_ptr)->GRID_PTR = *grid_ptr;
  (*group_ptr)->ELEM_PTR = *elem_ptr;
  (*group_ptr)->GRAMPEXC_PTR = *grampexc_ptr;
  (*group_ptr)->GRPHAEXC_PTR = *grphaexc_ptr;
  (*group_ptr)->ADDREM_PTR = *addrem_ptr;







  }
  return (0);
}
}
int grphaexc(struct charac *p1 , struct charac **pp2 , struct GrPhaExc **grphaexc_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  double unif_val ;
  double *unif_val_ptr ;
  double centre ;
  double *centre_ptr ;
  double p1_ep ;
  double *p1_ep_ptr ;
  double p2_ep ;
  double *p2_ep_ptr ;
  double q1_ep ;
  double *q1_ep_ptr ;
  double q2_ep ;
  double *q2_ep_ptr ;
  int angle_unit ;
  int *angle_unit_ptr ;
  int direction ;
  int *direction_ptr ;
  int omit_angle ;
  int *omit_angle_ptr ;
  double angle_start ;
  double *angle_start_ptr ;
  double angle_step ;
  double *angle_step_ptr ;
  int omit_phase ;
  int *omit_phase_ptr ;
  double phase_start ;
  double *phase_start_ptr ;
  double phase_step ;
  double *phase_step_ptr ;
  double u ;
  double *u_ptr ;
  double v ;
  double *v_ptr ;
  double theta ;
  double *theta_ptr ;
  double phi ;
  double *phi_ptr ;
  int phase_unit ;
  int *phase_unit_ptr ;
  void *tmp ;
  void *tmp___0 ;
  void *tmp___1 ;
  void *tmp___2 ;
  {
  {

  unif_val_ptr = & unif_val;
  centre_ptr = & centre;
  p1_ep_ptr = & p1_ep;
  p2_ep_ptr = & p2_ep;
  q1_ep_ptr = & q1_ep;
  q2_ep_ptr = & q2_ep;
  angle_unit_ptr = & angle_unit;
  direction_ptr = & direction;
  omit_angle_ptr = & omit_angle;
  angle_start_ptr = & angle_start;
  angle_step_ptr = & angle_step;
  omit_phase_ptr = & omit_phase;
  phase_start_ptr = & phase_start;
  phase_step_ptr = & phase_step;




  phase_unit_ptr = & phase_unit;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[43], curr_ptr);
  }




  {
  error = unifpha(*curr_ptr, curr_ptr, unif_val_ptr, phase_unit_ptr);
  }
  if (error == 0) {
    {
    tmp = malloc(sizeof(struct GrPhaExc ));
    *grphaexc_ptr = (struct GrPhaExc *)tmp;
    }






    (*grphaexc_ptr)->TYPE = 0;
    (*grphaexc_ptr)->UNIF_VAL = unif_val;



    return (0);
  }
  {
  error = secorpha(*curr_ptr, curr_ptr, centre_ptr, p1_ep_ptr, p2_ep_ptr, q1_ep_ptr,
                   q2_ep_ptr, phase_unit_ptr);
  }
  if (error == 17) {
    {

    printf((char const   * __restrict  )"\n%s", ErrorMessages[76]);
    }
    return (17);
  }
  if (error == 0) {
    {
    tmp___0 = malloc(sizeof(struct GrPhaExc ));
    *grphaexc_ptr = (struct GrPhaExc *)tmp___0;
    }






    (*grphaexc_ptr)->TYPE = 1;








    return (0);
  }
  {
  error = serotpha(*curr_ptr, curr_ptr, direction_ptr, omit_angle_ptr, angle_start_ptr,
                   angle_step_ptr, omit_phase_ptr, phase_start_ptr, phase_step_ptr,
                   angle_unit_ptr, phase_unit_ptr);
  }
  if (error == 17) {
    {

    printf((char const   * __restrict  )"\n%s", ErrorMessages[77]);
    }
    return (17);
  }
                  {
    {
    tmp___1 = malloc(sizeof(struct GrPhaExc ));
    *grphaexc_ptr = (struct GrPhaExc *)tmp___1;
    }






    (*grphaexc_ptr)->TYPE = 3;











    return (0);
  }


































}
}
int grwrite(struct Group *group_ptr , char *filename )
{
  int NEL ;
  int NPORTS ;
  int IDUM ;
  struct Geomnode *geomnode_ptr ;
  struct Geomport *geomport_ptr ;
  char datfilename[101] ;
  {







  {
  geomnode_ptr = group_ptr->GEOMNODE_PTR;
  strcpy((char * __restrict  )(datfilename), (char const   * __restrict  )filename);
  strcat((char * __restrict  )(datfilename), (char const   * __restrict  )".dat");
  printf((char const   * __restrict  )"\n** Writing output file: %s", datfilename);
  printf((char const   * __restrict  )"\n\nNEL \nNPORTS");
  printf((char const   * __restrict  )"\nIDUM      REXA     REYA     REZA     THEA     PHEA     PSEA ");
  printf((char const   * __restrict  )"\n          AMP      PSH      PSC      PHEPOL\n");
  NEL = group_ptr->NUM_OF_NODES;
  printf((char const   * __restrict  )"%4d", NEL);
  printf((char const   * __restrict  )"\n");
  printf((char const   * __restrict  )"%4d", NEL);
  printf((char const   * __restrict  )"\n");
  NPORTS = (group_ptr->ELEM_PTR)->NPORTS;
  printf((char const   * __restrict  )"%4d", NPORTS);
  printf((char const   * __restrict  )"\n");
  printf((char const   * __restrict  )"%4d", NPORTS);
  printf((char const   * __restrict  )"\n");
  }
  {
  while (1) {
                                     ;
    if (! ((unsigned long )geomnode_ptr != (unsigned long )((void *)0))) {
      goto while_break;
    }
    {
    IDUM ++;
    printf((char const   * __restrict  )"%4d ", IDUM);
    printf((char const   * __restrict  )"\t%8.2f ", geomnode_ptr->XA);
    printf((char const   * __restrict  )"%8.2f ", geomnode_ptr->YA);
    printf((char const   * __restrict  )"%8.2f ", geomnode_ptr->ZA);
    printf((char const   * __restrict  )"%8.2f ", geomnode_ptr->THEA);
    printf((char const   * __restrict  )"%8.2f ", geomnode_ptr->PHEA);
    printf((char const   * __restrict  )"%8.2f", geomnode_ptr->PSEA);
    printf((char const   * __restrict  )"\n");
    printf((char const   * __restrict  )"%4d ", IDUM);
    printf((char const   * __restrict  )"\t%8.2f ", geomnode_ptr->XA);
    printf((char const   * __restrict  )"%8.2f ", geomnode_ptr->YA);
    printf((char const   * __restrict  )"%8.2f ", geomnode_ptr->ZA);
    printf((char const   * __restrict  )"%8.2f ", geomnode_ptr->THEA);
    printf((char const   * __restrict  )"%8.2f ", geomnode_ptr->PHEA);
    printf((char const   * __restrict  )"%8.2f", geomnode_ptr->PSEA);
    printf((char const   * __restrict  )"\n");
    geomport_ptr = geomnode_ptr->GEOMPORT_PTR;
    }
    {

                                           ;



      {
      printf((char const   * __restrict  )"   \t%8.2f ", geomport_ptr->AMP);
      printf((char const   * __restrict  )"%8.2f ", geomport_ptr->PSH + geomport_ptr->PPA);
      printf((char const   * __restrict  )"%8.2f ", geomport_ptr->PSC);
      printf((char const   * __restrict  )"%8.2f", geomport_ptr->PHEPOL);
      printf((char const   * __restrict  )"\n");
      printf((char const   * __restrict  )"   \t%8.2f ", geomport_ptr->AMP);
      printf((char const   * __restrict  )"%8.2f ", geomport_ptr->PSH + geomport_ptr->PPA);
      printf((char const   * __restrict  )"%8.2f ", geomport_ptr->PSC);
      printf((char const   * __restrict  )"%8.2f", geomport_ptr->PHEPOL);
      printf((char const   * __restrict  )"\n");

      }



    }
    geomnode_ptr = geomnode_ptr->NEXT;
  }
  while_break: /* CIL Label */ ;
  }
  {
  printf((char const   * __restrict  )"\n** End writing output file: %s \n", datfilename);
  }
  return (0);
}
}
int hexdef(struct charac *p1 , struct charac **pp2 , struct Node **node_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  int pcoord ;
  int *pcoord_ptr ;
  int qcoord ;
  int *qcoord_ptr ;
  void *tmp ;
  {
  {

  pcoord_ptr = & pcoord;
  qcoord_ptr = & qcoord;
  *curr_ptr = p1;


  error = GetKeyword(Keywords[78], curr_ptr);
  }



  {
  error = nodecoor(*curr_ptr, curr_ptr, pcoord_ptr, qcoord_ptr);
  }






  if (error == 17) {



    return (17);
  }
  {
  tmp = malloc(sizeof(struct Node ));
  *node_ptr = (struct Node *)tmp;
  }







  (*node_ptr)->PCOORD = pcoord;
  (*node_ptr)->QCOORD = qcoord;




  *pp2 = *curr_ptr;


}
}
int hexgrdef(struct charac *p1 , struct charac **pp2 , double *pstep_ptr , int *pstep_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {

  *curr_ptr = p1;



  error = GetKeyword(Keywords[22], curr_ptr);
  }



  {
  error = sinstep(*curr_ptr, curr_ptr, pstep_ptr, pstep_unit_ptr);
  }















  *pp2 = *curr_ptr;
  return (0);
}
}
int InKWords(char *WORD )
{
  int i ;
  size_t tmp ;
  int tmp___0 ;
  {


























  return (0);
}
}






















































int intmax(int a , int b )
{
  if (a > b) {
    return (a);
  } else {
    return (b);
  }



}
int intmin(int a , int b )
{
  if (a < b) {
    return (a);
  } else {
    return (b);
  }

}





































int isletter(char ch )
{
  unsigned short const   **tmp ;
  {
  {
  tmp = __ctype_b_loc();
  }
  if ((int const   )*(*tmp + (int )ch) & 1024) {

  } else { //Added block


            //Added block



    return (0);



  }
}
}
void kwdsinit(void)
{
  char i ;
  size_t tmp ;
  {


















  strcpy((char * __restrict  )(Keywords[5]), (char const   * __restrict  )"RADIUS");








  strcpy((char * __restrict  )(Keywords[14]), (char const   * __restrict  )"GRID");
  strcpy((char * __restrict  )(Keywords[15]), (char const   * __restrict  )"LINEAR");
  strcpy((char * __restrict  )(Keywords[16]), (char const   * __restrict  )"STEP");
  strcpy((char * __restrict  )(Keywords[17]), (char const   * __restrict  )"SQUARE");
  strcpy((char * __restrict  )(Keywords[18]), (char const   * __restrict  )"RECTANGULAR");



  strcpy((char * __restrict  )(Keywords[22]), (char const   * __restrict  )"HEXAGONAL");





  strcpy((char * __restrict  )(Keywords[28]), (char const   * __restrict  )"ELEMENT");
  strcpy((char * __restrict  )(Keywords[29]), (char const   * __restrict  )"GEOMETRY");

  strcpy((char * __restrict  )(Keywords[31]), (char const   * __restrict  )"POLARIZATION");






  strcpy((char * __restrict  )(Keywords[38]), (char const   * __restrict  )"CIRCULAR");
  strcpy((char * __restrict  )(Keywords[39]), (char const   * __restrict  )"PORTS");
  strcpy((char * __restrict  )(Keywords[40]), (char const   * __restrict  )"PORT");

  strcpy((char * __restrict  )(Keywords[42]), (char const   * __restrict  )"AMPLITUDE");
  strcpy((char * __restrict  )(Keywords[43]), (char const   * __restrict  )"PHASE");



  strcpy((char * __restrict  )(Keywords[47]), (char const   * __restrict  )"GROUP");




  strcpy((char * __restrict  )(Keywords[52]), (char const   * __restrict  )"rad");












  strcpy((char * __restrict  )(Keywords[65]), (char const   * __restrict  )"LH");

  strcpy((char * __restrict  )(Keywords[67]), (char const   * __restrict  )"PHASE_SHAPING");
  strcpy((char * __restrict  )(Keywords[68]), (char const   * __restrict  )"PHASE_SCANNING");
  strcpy((char * __restrict  )(Keywords[69]), (char const   * __restrict  )"PHASE_POL_ARRANG");



  strcpy((char * __restrict  )(Keywords[73]), (char const   * __restrict  )"NODE");


  strcpy((char * __restrict  )(Keywords[76]), (char const   * __restrict  )"BLOCK");

  strcpy((char * __restrict  )(Keywords[78]), (char const   * __restrict  )"HEXAGON");
  strcpy((char * __restrict  )(Keywords[79]), (char const   * __restrict  )"ADD");

  strcpy((char * __restrict  )(Keywords[81]), (char const   * __restrict  )"SECOND");
  strcpy((char * __restrict  )(Keywords[82]), (char const   * __restrict  )"ORDER");
  strcpy((char * __restrict  )(Keywords[83]), (char const   * __restrict  )"CENTRE");




  strcpy((char * __restrict  )(Keywords[88]), (char const   * __restrict  )"UNIFORM");
  strcpy((char * __restrict  )(Keywords[89]), (char const   * __restrict  )"P1_VAL");
  strcpy((char * __restrict  )(Keywords[90]), (char const   * __restrict  )"P2_VAL");
  strcpy((char * __restrict  )(Keywords[91]), (char const   * __restrict  )"Q1_VAL");







  strcpy((char * __restrict  )(Keywords[99]), (char const   * __restrict  )"ROTATION");
  strcpy((char * __restrict  )(Keywords[100]), (char const   * __restrict  )"SEQUENTIAL");
  strcpy((char * __restrict  )(Keywords[101]), (char const   * __restrict  )"GROUP_EXCITATION");















































}
}

















































































int linpol(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[15], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }



                  {


    *pp2 = *curr_ptr;

  }









}
}
int mksblock(struct AddRem *addrem_ptr , struct Geomnode **first_node_ptr , struct Geomnode **last_node_ptr ,
             double pstep , double qstep , double angle , int *nodes_num_ptr , int elem_shape ,
             double elem_pdim , double elem_qdim )
{
  struct Geomnode *app_ptr ;
  struct Geomnode *primo_ptr ;
  struct Geomnode *ultimo_ptr ;
  int p ;
  int q ;
  int p1 ;
  int q1 ;
  int p2 ;
  int q2 ;
  double x ;
  double y ;
  int *pp1 ;
  int *pp2 ;
  int *qq1 ;
  int *qq2 ;
  void *tmp ;
  double tmp___0 ;
  double tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  {
  {

  primo_ptr = (struct Geomnode *)((void *)0);





  p1 = (addrem_ptr->NODE_PTR)->PCOORD;
  q1 = (addrem_ptr->NODE_PTR)->QCOORD;
  p2 = ((addrem_ptr->NODE_PTR)->NEXT)->PCOORD;
  q2 = ((addrem_ptr->NODE_PTR)->NEXT)->QCOORD;
  *nodes_num_ptr = 0;
  q = intmin(q1, q2);
  }
  {
  while (1) {
                                     ;
    {
    tmp___3 = intmax(q1, q2);
    }
    if (! (q <= tmp___3)) {
      goto while_break;
    }
    {
    p = intmin(p1, p2);
    }
    {
    while (1) {
                                           ;
      {
      tmp___2 = intmax(p1, p2);
      }
      if (! (p <= tmp___2)) {
        goto while_break___0;
      }
      {
      tmp = malloc(sizeof(struct Geomnode ));
      app_ptr = (struct Geomnode *)tmp;
      }






      {
      tmp___0 = dsin(angle);
      y = ((double )q * qstep) * tmp___0;
      tmp___1 = dcos(angle);
      x = (double )p * pstep + ((double )q * qstep) * tmp___1;
      (*nodes_num_ptr) ++;


      app_ptr->XA = x;
      app_ptr->YA = y;








      }
      if ((unsigned long )primo_ptr == (unsigned long )((void *)0)) {
        primo_ptr = app_ptr;
      } else {
        ultimo_ptr->NEXT = app_ptr;
      }
      ultimo_ptr = app_ptr;


      p ++;
    }
    while_break___0: /* CIL Label */ ;
    }
    q ++;
  }
  while_break: /* CIL Label */ ;
  }
  *first_node_ptr = primo_ptr;
  *last_node_ptr = ultimo_ptr;
  return (0);
}
}
int mkshex(struct AddRem *addrem_ptr , struct Geomnode **first_node_ptr , struct Geomnode **last_node_ptr ,
           double pstep , double qstep , double angle , int *nodes_num_ptr , int elem_shape ,
           double elem_pdim , double elem_qdim )
{
  struct Geomnode *app_ptr ;
  struct Geomnode *primo_ptr ;
  struct Geomnode *ultimo_ptr ;
  int p ;
  int q ;
  int P[8] ;
  int Q[8] ;
  int i ;
  double x ;
  double y ;
  void *tmp ;
  double tmp___0 ;
  double tmp___1 ;
  {

  primo_ptr = (struct Geomnode *)((void *)0);

  p = (addrem_ptr->NODE_PTR)->PCOORD;
  q = (addrem_ptr->NODE_PTR)->QCOORD;

  P[1] = p - 1;
  Q[1] = q + 1;
  P[2] = p;
  Q[2] = q + 1;
  P[3] = p + 1;
  Q[3] = q;
  P[4] = p + 1;
  Q[4] = q - 1;
  P[5] = p;
  Q[5] = q - 1;
  P[6] = p - 1;
  Q[6] = q;
  P[7] = p;
  Q[7] = q;
  i = 1;
  {
  while (1) {
                                     ;
    if (! (i <= 7)) {
      goto while_break;
    }
    {
    tmp = malloc(sizeof(struct Geomnode ));
    app_ptr = (struct Geomnode *)tmp;
    }






    {
    tmp___0 = dcos(angle);
    x = (double )P[i] * pstep + ((double )Q[i] * qstep) * tmp___0;
    tmp___1 = dsin(angle);
    y = ((double )Q[i] * qstep) * tmp___1;
    (*nodes_num_ptr) ++;


    app_ptr->XA = x;
    app_ptr->YA = y;








    }
    if ((unsigned long )primo_ptr == (unsigned long )((void *)0)) {
      primo_ptr = app_ptr;
    } else {
      ultimo_ptr->NEXT = app_ptr;
    }
    ultimo_ptr = app_ptr;

    i ++;
  }
  while_break: /* CIL Label */ ;
  }
  *first_node_ptr = primo_ptr;
  *last_node_ptr = ultimo_ptr;
  return (0);
}
}































































































































































void moseinit(void)
{
  int i ;
  {















  strcpy((char * __restrict  )(MOSErrors[2]), (char const   * __restrict  )"** WARNING B2: GRID step(s) too small for specified element in GROUP: ");


  strcpy((char * __restrict  )(MOSErrors[5]), (char const   * __restrict  )"** ERROR  B5: SECOND ORDER law not allowed on irregular groups.");



  strcpy((char * __restrict  )(MOSErrors[9]), (char const   * __restrict  )"** ERROR  B9: PHASE excitation error in GROUP: ");

  strcpy((char * __restrict  )(MOSErrors[11]), (char const   * __restrict  )"** ERROR B11: SEQUENTIAL ROTATION not allowed on irregular shaped groups.");











}
}
int nodecoor(struct charac *p1 , struct charac **pp2 , int *pcoord_ptr , int *qcoord_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;



  error = GetInt(*curr_ptr, curr_ptr, pcoord_ptr);
  }



  {


  error = GetInt(*curr_ptr, curr_ptr, qcoord_ptr);
  }




  *pp2 = *curr_ptr;
  return (0);
}
}
int nodedef(struct charac *p1 , struct charac **pp2 , struct Node **node_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  int pcoord ;
  int *pcoord_ptr ;
  int qcoord ;
  int *qcoord_ptr ;
  double thea ;
  double *thea_ptr ;
  double phea ;
  double *phea_ptr ;
  double psea ;
  double *psea_ptr ;
  int angle_unit ;
  int *angle_unit_ptr ;
  int omit_orient ;
  void *tmp ;
  {
  {
  curr_ptr = & curr;
  pcoord_ptr = & pcoord;
  qcoord_ptr = & qcoord;




  *curr_ptr = p1;



  error = GetKeyword(Keywords[73], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = nodecoor(*curr_ptr, curr_ptr, pcoord_ptr, qcoord_ptr);
  }












































  *pp2 = *curr_ptr;

}
}




























































void nomefile(char *fn )
{
  strcpy((char * __restrict  )fn, (char const   * __restrict  )(GLOBLE_FILENAME));





}
static int errline_printed  =    0;
void parserro(struct charac *err_ptr , int errcode , char *s )
{
  struct charac *p ;
  int n ;
  int i ;
  {
  n = 0;
  p = err_ptr;
  if (! errline_printed) {
    {
    errline_printed = 1;
    printf((char const   * __restrict  )"\nError occurred at line %d", err_ptr->LINE_NUM);
    }
    {
    while (1) {
                                       ;
                                                                  {
        if (! ((p->PREV)->LINE_NUM == err_ptr->LINE_NUM)) {
          goto while_break;
        }
      }


      n ++;
      p = p->PREV;
    }
    while_break: /* CIL Label */ ;
    }
    {
    printf((char const   * __restrict  )"\n%4d:\t", p->LINE_NUM);
    }
    {
    while (1) {
                                           ;
                                                            {
        if (! (p->LINE_NUM == err_ptr->LINE_NUM)) {
          goto while_break___0;
        }
      }


      {
      printf((char const   * __restrict  )"%c", (int )p->info);
      p = p->NEXT;
      }
    }
    while_break___0: /* CIL Label */ ;
    }
    {
    printf((char const   * __restrict  )"\n%    \t");
    i = 1;
    }
    {
    while (1) {
                                           ;
      if (! (i <= n)) {
        goto while_break___1;
      }
      {
      printf((char const   * __restrict  )" ");
      i ++;
      }
    }
    while_break___1: /* CIL Label */ ;
    }
    {
    printf((char const   * __restrict  )"^");
    }
  }




         {

    printf((char const   * __restrict  )"\n%s%s\n", ErrorMessages[errcode], s);

  }

}
}

















































































































































int polspec(struct charac *p1 , struct charac **pp2 , int *polarization_ptr , double *phepol_ptr ,
            int *phepol_unit_ptr , int *direction_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {

  *curr_ptr = p1;





  error = GetKeyword(Keywords[31], curr_ptr);
  }



  {

  error = linpol(*curr_ptr, curr_ptr, phepol_ptr, phepol_unit_ptr);
  }










  {

  error = circpol(*curr_ptr, curr_ptr, direction_ptr);
  }
  if (error == 0) {
    *pp2 = *curr_ptr;
    return (0);
  }







}
}




















































































int portamp(struct charac *p1 , struct charac **pp2 , double *amp_ptr , int *amp_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[42], curr_ptr);
  }



  {
  error = ampval(*curr_ptr, curr_ptr, amp_ptr, amp_unit_ptr);
  }







  *pp2 = *curr_ptr;
  return (0);
}
}
int portdef(struct charac *p1 , struct charac **pp2 , struct Port *PORT_PTR , int *portnum_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  double amp ;
  double *amp_ptr ;
  int amp_unit ;
  int *amp_unit_ptr ;
  double psc ;
  double *psc_ptr ;
  int psc_unit ;
  int *psc_unit_ptr ;
  double psh ;
  double *psh_ptr ;
  int psh_unit ;
  int *psh_unit_ptr ;
  double ppa ;
  double *ppa_ptr ;
  int ppa_unit ;
  int *ppa_unit_ptr ;
  double phepol ;
  double *phepol_ptr ;
  int phepol_unit ;
  int *phepol_unit_ptr ;
  int omit_pol ;
  int *omit_pol_ptr ;
  {
  {
  curr_ptr = & curr;
  amp_ptr = & amp;
  amp_unit_ptr = & amp_unit;
  psc_ptr = & psc;
  psc_unit_ptr = & psc_unit;
  psh_ptr = & psh;
  psh_unit_ptr = & psh_unit;
  ppa_ptr = & ppa;
  ppa_unit_ptr = & ppa_unit;



  *curr_ptr = p1;

  error = GetKeyword(Keywords[40], curr_ptr);
  }
  if (error != 0) {
    {
    parserro(*curr_ptr, 1, Keywords[40]);
    }
    return (1);
  }
  {
  error = GetNatur(*curr_ptr, curr_ptr, portnum_ptr);
  }





















  {
  error = portamp(*curr_ptr, curr_ptr, amp_ptr, amp_unit_ptr);
  }






  {
  error = pshdef1(*curr_ptr, curr_ptr, psh_ptr, psh_unit_ptr);
  }










  {
  error = pscdef1(*curr_ptr, curr_ptr, psc_ptr, psc_unit_ptr);
  }










  {
  error = ppadef1(*curr_ptr, curr_ptr, ppa_ptr, ppa_unit_ptr);
  }





















  *pp2 = *curr_ptr;


}
}
int portspec(struct charac *p1 , struct charac **pp2 , int *nports_ptr , struct Port **port_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  int n ;
  int portnum ;
  int *portnum_ptr ;
  struct Port *primo_ptr ;
  struct Port *ultimo_ptr ;
  struct Port *app_ptr ;
  void *tmp ;
  {
  {

  portnum_ptr = & portnum;



  *curr_ptr = p1;

  error = GetKeyword(Keywords[39], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = GetNatur(*curr_ptr, curr_ptr, nports_ptr);
  }







  n = 1;
  {
  while (1) {
                                     ;
    if (! (n <= *nports_ptr)) {
      goto while_break;
    }
    {
    tmp = malloc(sizeof(struct Port ));
    app_ptr = (struct Port *)tmp;
    }






    {
    error = portdef(*curr_ptr, curr_ptr, app_ptr, portnum_ptr);
    }
    if (error == 1) {
      {
      parserro(*curr_ptr, 46, (char *)" ");
      }
      return (17);
    }














    n ++;
  }
  while_break: /* CIL Label */ ;
  }

  *pp2 = *curr_ptr;


}
}
int ppadef1(struct charac *p1 , struct charac **pp2 , double *ppa_ptr , int *ppa_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {

  *curr_ptr = p1;

  error = GetKeyword(Keywords[69], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = angval(*curr_ptr, curr_ptr, ppa_ptr, ppa_unit_ptr);
  }






  *pp2 = *curr_ptr;

}
}






















































void prnfile(struct charac *firstel )
{
  struct charac *p ;
  char ch ;
  int line_num ;
  {
  {

  line_num = 0;
  printf((char const   * __restrict  )"\n");
  p = firstel;
  }
  {
  while (1) {
                                     ;
    if (! ((unsigned long )p->NEXT != (unsigned long )((void *)0))) {
      goto while_break;
    }
    ch = p->info;
    if (p->LINE_NUM > line_num) {

      line_num = p->LINE_NUM;
      printf((char const   * __restrict  )"\n%4d\t", line_num);

    }
    {
    putchar((int )ch);
    p = p->NEXT;
    }
  }
  while_break: /* CIL Label */ ;
  }
  {
  printf((char const   * __restrict  )"\n");
  }


}
}
int pscdef1(struct charac *p1 , struct charac **pp2 , double *psc_ptr , int *psc_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {

  *curr_ptr = p1;

  error = GetKeyword(Keywords[68], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = angval(*curr_ptr, curr_ptr, psc_ptr, psc_unit_ptr);
  }






  *pp2 = *curr_ptr;


}
}
int pshdef1(struct charac *p1 , struct charac **pp2 , double *psh_ptr , int *psh_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[67], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = angval(*curr_ptr, curr_ptr, psh_ptr, psh_unit_ptr);
  }






  *pp2 = *curr_ptr;


}
}
int readfil3(char *filename , struct charac **firstel , struct charac **lastel )
{
  FILE *f ;
  char c ;
  struct charac *p ;
  int line_num ;
  char CR ;
  char adlfilename[101] ;
  int tmp ;
  int tmp___0 ;
  unsigned short const   **tmp___1 ;
  void *tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  unsigned short const   **tmp___5 ;
  void *tmp___6 ;
  void *tmp___7 ;
  int tmp___8 ;
  unsigned short const   **tmp___9 ;
  {
  {
  line_num = 1;
  CR = (char )'\n';


  strcpy((char * __restrict  )(adlfilename), (char const   * __restrict  )filename);
  strcat((char * __restrict  )(adlfilename), (char const   * __restrict  )".adl");
  f = fopen((char const   * __restrict  )(adlfilename), (char const   * __restrict  )"r");
  }






  {
  tmp = _IO_getc(f);
  c = (char )tmp;
  }



























  {
  tmp___2 = malloc(sizeof(struct charac ));
  p = (struct charac *)tmp___2;
  }






  {
  p->info = c;
  p->LINE_NUM = line_num;


  *firstel = p;
  *lastel = p;
  printf((char const   * __restrict  )"\n");
  tmp___3 = _IO_getc(f);
  c = (char )tmp___3;
  }
  {
  while (1) {
                                         ;
    if (! ((int )c != -1)) {
      goto while_break___0;
    }
    {
    tmp___9 = __ctype_b_loc();
    }
    if ((int const   )*(*tmp___9 + (int )c) & 8192) {
      goto _L;
    } else { //Added block
    if ((int )c == 44) {
      _L:
      {
      while (1) {
                                             ;
        if ((int )c == (int )CR) {
          line_num ++;
        }
        {
        tmp___4 = _IO_getc(f);
        c = (char )tmp___4;
        tmp___5 = __ctype_b_loc();
        }
        if (! ((int const   )*(*tmp___5 + (int )c) & 8192)) {

            goto while_break___1;

        }
      }
      while_break___1: /* CIL Label */ ;
      }
      {
      tmp___6 = malloc(sizeof(struct charac ));
      p = (struct charac *)tmp___6;
      }






      p->info = (char )' ';
      p->LINE_NUM = line_num;
      p->PREV = *lastel;

      (*lastel)->NEXT = p;
      *lastel = p;
    } else {
      {
      tmp___7 = malloc(sizeof(struct charac ));
      p = (struct charac *)tmp___7;
      }
      if ((unsigned long )p == (unsigned long )((void *)0)) {



        return (22);
      }
      {
      p->info = c;
      p->LINE_NUM = line_num;
      p->PREV = *lastel;

      (*lastel)->NEXT = p;
      *lastel = p;
      tmp___8 = _IO_getc(f);
      c = (char )tmp___8;
      }
    }
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  {
  fclose(f);
  }


}
}
int recgrdef(struct charac *p1 , struct charac **pp2 , double *pstep_ptr , double *qstep_ptr ,
             int *pqstep_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;




  error = GetKeyword(Keywords[18], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }



                  {



    *pp2 = *curr_ptr;
    return (0);
  }












}
}
int recspec(struct charac *p1 , struct charac **pp2 , double *pdim_ptr , double *qdim_ptr ,
            int *pqdim_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[18], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {


  error = Get1Real(*curr_ptr, curr_ptr, pdim_ptr);
  }






  {


  error = Get1Real(*curr_ptr, curr_ptr, qdim_ptr);
  }












  *pp2 = *curr_ptr;

}
}






































































































































































































































int secorpha(struct charac *p1 , struct charac **pp2 , double *centre_ptr , double *p1_ep_ptr ,
             double *p2_ep_ptr , double *q1_ep_ptr , double *q2_ep_ptr , int *phase_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[81], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = GetKeyword(Keywords[82], curr_ptr);

  error = GetKeyword(Keywords[83], curr_ptr);

  error = GetReal(centre_ptr, curr_ptr);
  }






  {
  error = GetKeyword(Keywords[89], curr_ptr);

  error = GetReal(p1_ep_ptr, curr_ptr);
  }






  {
  error = GetKeyword(Keywords[90], curr_ptr);

  error = GetReal(p2_ep_ptr, curr_ptr);
  }






  {
  error = GetKeyword(Keywords[91], curr_ptr);

  error = GetReal(q1_ep_ptr, curr_ptr);
  }











  if (error != 0) {
    {
    parserro(*curr_ptr, 68, (char *)" ");
    }
    return (17);
  }

  return (0);
}
}






































































































































































































































































































int serotpha(struct charac *p1 , struct charac **pp2 , int *direction_ptr , int *omit_angle_ptr ,
             double *angle_start_ptr , double *angle_step_ptr , int *omit_phase_ptr ,
             double *phase_start_ptr , double *phase_step_ptr , int *angle_unit_ptr ,
             int *phase_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {

  *curr_ptr = p1;



  error = GetKeyword(Keywords[99], curr_ptr);
  }



  {
  error = GetKeyword(Keywords[100], curr_ptr);
  }
  if (error != 0) {
    {
    parserro(*curr_ptr, 1, Keywords[100]);
    }
    return (17);
  }


















}
}




































































































































































































int sgrampun(struct GrAmpExc *grampexc_ptr , struct Geomnode *geomnode_ptr , struct Port *port_ptr )
{
  struct Geomport *primo_ptr ;
  struct Geomport *app_ptr ;
  struct Geomport *ultimo_ptr ;
  struct Geomnode *geomnode_app_ptr ;
  struct Port *port_app_ptr ;
  double unif_val ;
  void *tmp ;
  {





  unif_val = grampexc_ptr->UNIF_VAL;


  {
  while (1) {
                                     ;
    if (! ((unsigned long )geomnode_app_ptr != (unsigned long )((void *)0))) {
      goto while_break;
    }



    port_app_ptr = port_ptr;
    {

                                           ;



      {
      tmp = malloc(sizeof(struct Geomport ));
      app_ptr = (struct Geomport *)tmp;
      }






      app_ptr->AMP = unif_val * port_app_ptr->AMP;
                                                                    {
        primo_ptr = app_ptr;
      }








    }
    geomnode_app_ptr->GEOMPORT_PTR = primo_ptr;
    geomnode_app_ptr = geomnode_app_ptr->NEXT;
  }
  while_break: /* CIL Label */ ;
  }
  return (0);
}
}
int sgrpha2n(struct GrPhaExc *grphaexc_ptr , struct Geomnode *geomnode_ptr , struct Port *port_ptr ,
             int group_shape )
{
  struct Geomport *geomport_app_ptr ;
  struct Geomnode *geomnode_app_ptr ;
  struct Port *port_app_ptr ;
  struct Geomnode *pmin_tp ;
  struct Geomnode **pmin_ptr ;
  struct Geomnode *pmax_tp ;
  struct Geomnode **pmax_ptr ;
  struct Geomnode *qmin_tp ;
  struct Geomnode **qmin_ptr ;
  struct Geomnode *qmax_tp ;
  struct Geomnode **qmax_ptr ;
  double centre ;
  double p1_ep ;
  double p2_ep ;
  double q1_ep ;
  double q2_ep ;
  double a ;
  double b ;
  double c ;
  double d ;
  double e ;
  double x1 ;
  double y1___0 ;
  double A ;
  double B ;
  double C ;
  double D ;
  double E ;
  double phase_val ;
  double p1x ;
  double p1y ;
  double p2x ;
  double p2y ;
  double q1x ;
  double q1y ;
  double q2x ;
  double q2y ;
  double cex ;
  double cey ;
  double Hx[8] ;
  double Hy[8] ;
  int i ;
  {






























            //Added block


































    {
    printf((char const   * __restrict  )"\n%s", MOSErrors[5]);
    }
    return (5);
























































}
}
int sgrphasr(struct Group *group_ptr )
{
  struct Geomnode *geomnode_app_ptr ;
  double angle_start ;
  double angle_step ;
  double phase_start ;
  double phase_step ;
  double sign ;
  {








    {
    printf((char const   * __restrict  )"\n%s", MOSErrors[11]);
    }
    return (11);































































}
}
int sgrphaun(struct GrPhaExc *grphaexc_ptr , struct Geomnode *geomnode_ptr , struct Port *port_ptr )
{
  struct Geomport *geomport_app_ptr ;
  struct Geomnode *geomnode_app_ptr ;
  struct Port *port_app_ptr ;
  double unif_val ;
  {



  unif_val = grphaexc_ptr->UNIF_VAL;
  geomnode_app_ptr = geomnode_ptr;
  {
  while (1) {
                                     ;
    if (! ((unsigned long )geomnode_app_ptr != (unsigned long )((void *)0))) {
      goto while_break;
    }
    geomport_app_ptr = geomnode_app_ptr->GEOMPORT_PTR;
    port_app_ptr = port_ptr;
    {

                                           ;



      geomport_app_ptr->PSH = unif_val + port_app_ptr->PSH;






    }
    geomnode_app_ptr = geomnode_app_ptr->NEXT;
  }
  while_break: /* CIL Label */ ;
  }
  return (0);
}
}













































int simamp(struct Group *group_ptr )
{
  int error ;
  {












  case_0: /* CIL Label */
       {
  error = sgrampun(group_ptr->GRAMPEXC_PTR, group_ptr->GEOMNODE_PTR, (group_ptr->ELEM_PTR)->PORT_PTR);
  }


















}
}
int simgroup(struct Group *group_ptr )
{
  int error ;
  {


  fixsgrel(group_ptr);
  error = addscan(group_ptr);










}
}
int simpha(struct Group *group_ptr )
{
  int error ;
  {




  {
  if ((group_ptr->GRPHAEXC_PTR)->TYPE == 0) {
    goto case_0;
  }
  if ((group_ptr->GRPHAEXC_PTR)->TYPE == 1) {
    goto case_1;
  }
                                            {
    goto case_3;
  }

  case_0: /* CIL Label */
  {
  error = sgrphaun(group_ptr->GRPHAEXC_PTR, group_ptr->GEOMNODE_PTR, (group_ptr->ELEM_PTR)->PORT_PTR);
  }
  goto switch_break;
  case_1: /* CIL Label */
  {
  error = sgrpha2n(group_ptr->GRPHAEXC_PTR, group_ptr->GEOMNODE_PTR, (group_ptr->ELEM_PTR)->PORT_PTR,
                   group_ptr->SHAPE);
  }
  goto switch_break;
  case_3: /* CIL Label */
  {
  error = sgrphasr(group_ptr);
  }

  switch_break: /* CIL Label */ ;
  }
  if (error != 0) {
    {
    printf((char const   * __restrict  )"\n%s%s", MOSErrors[9], group_ptr->NAME);
    }
    return (9);
  } else {


  }
}
}
int simpol(struct Group *group_ptr )
{
  struct Geomport *geomport_app_ptr ;
  struct Geomnode *geomnode_app_ptr ;
  struct Port *port_app_ptr ;
  {
  geomnode_app_ptr = group_ptr->GEOMNODE_PTR;
  {
  while (1) {
                                     ;
    if (! ((unsigned long )geomnode_app_ptr != (unsigned long )((void *)0))) {
      goto while_break;
    }
    geomport_app_ptr = geomnode_app_ptr->GEOMPORT_PTR;
    port_app_ptr = (group_ptr->ELEM_PTR)->PORT_PTR;
    {

                                           ;



      geomport_app_ptr->PHEPOL = port_app_ptr->PHEPOL;
      port_app_ptr = port_app_ptr->NEXT;




    }
    geomnode_app_ptr = geomnode_app_ptr->NEXT;
  }
  while_break: /* CIL Label */ ;
  }
  return (0);
}
}
int sinelem(struct charac *p1 , struct charac **pp2 , struct Elem **elem_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  int geometry ;
  int *geometry_ptr ;
  double radius ;
  double *radius_ptr ;
  int radius_unit ;
  int *radius_unit_ptr ;
  double pdim ;
  double *pdim_ptr ;
  double qdim ;
  double *qdim_ptr ;
  int pqdim_unit ;
  int *pqdim_unit_ptr ;
  int model ;
  int *model_ptr ;
  double exp___0 ;
  double *exp_ptr ;
  double anglee ;
  double *anglee_ptr ;
  double angleh ;
  double *angleh_ptr ;
  int angle_unit ;
  int *angle_unit_ptr ;
  double tapere ;
  double *tapere_ptr ;
  double taperh ;
  double *taperh_ptr ;
  int taper_unit ;
  int *taper_unit_ptr ;
  int polarization ;
  int *polarization_ptr ;
  double phepol ;
  double *phepol_ptr ;
  int phepol_unit ;
  int *phepol_unit_ptr ;
  int direction ;
  int *direction_ptr ;
  double gain ;
  double *gain_ptr ;
  int gain_unit ;
  int *gain_unit_ptr ;
  int nports ;
  int *nports_ptr ;
  struct Port *p_ptr ;
  struct Port **port_ptr ;
  {
  {
  curr_ptr = & curr;
  geometry_ptr = & geometry;
  radius_ptr = & radius;
  radius_unit_ptr = & radius_unit;
  pdim_ptr = & pdim;
  qdim_ptr = & qdim;
  pqdim_unit_ptr = & pqdim_unit;








  polarization_ptr = & polarization;
  phepol_ptr = & phepol;
  phepol_unit_ptr = & phepol_unit;
  direction_ptr = & direction;


  nports_ptr = & nports;
  port_ptr = & p_ptr;
  *curr_ptr = p1;

  error = geomspec(*curr_ptr, curr_ptr, geometry_ptr, radius_ptr, radius_unit_ptr,
                   pdim_ptr, qdim_ptr, pqdim_unit_ptr);
  }










                  {

    error = polspec(*curr_ptr, curr_ptr, polarization_ptr, phepol_ptr, phepol_unit_ptr,
                    direction_ptr);

  }















                  {

    error = portspec(*curr_ptr, curr_ptr, nports_ptr, port_ptr);

  }
  if (error == 17) {
    {
    printf((char const   * __restrict  )"\n%s", ErrorMessages[49]);
    }
    return (17);
  }





  {


  (*elem_ptr)->GEOMETRY = geometry;
  (*elem_ptr)->RADIUS = radius;

  (*elem_ptr)->PDIM = pdim;
  (*elem_ptr)->QDIM = qdim;

















  *pp2 = *curr_ptr;
  }


}
}
int sinstep(struct charac *p1 , struct charac **pp2 , double *step_ptr , int *step_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;



  error = GetKeyword(Keywords[16], curr_ptr);
  }



  {
  error = GetUReal(*curr_ptr, curr_ptr, step_ptr);
  }
  if (error != 0) {

    return (error);
  }






  *pp2 = *curr_ptr;


}
}
int squgrdef(struct charac *p1 , struct charac **pp2 , double *pstep_ptr , int *pstep_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;



  error = GetKeyword(Keywords[17], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = sinstep(*curr_ptr, curr_ptr, pstep_ptr, pstep_unit_ptr);
  }














  *pp2 = *curr_ptr;


}
}
char TapeGet(struct charac **tp )
{
  char ch ;
  {


         {

    ch = (*tp)->info;
    *tp = (*tp)->NEXT;
  }
  return (ch);
}
}
int trigrdef(struct charac *p1 , struct charac **pp2 , double *angle_ptr , int *angle_unit_ptr ,
             double *pstep_ptr , double *qstep_ptr , int *pqstep_unit_ptr , double *px_ptr ,
             double *py_ptr , double *qx_ptr , double *qy_ptr , int *pqxy_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {

















    return (1);
















































}
}






















int unifamp(struct charac *p1 , struct charac **pp2 , double *unif_val_ptr , int *amp_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;
  {
  {

  *curr_ptr = p1;

  error = GetKeyword(Keywords[88], curr_ptr);
  }



  {
  error = ampval(*curr_ptr, curr_ptr, unif_val_ptr, amp_unit_ptr);
  }





  *pp2 = *curr_ptr;
  return (0);
}
}
int unifpha(struct charac *p1 , struct charac **pp2 , double *unif_val_ptr , int *phase_unit_ptr )
{
  struct charac *curr ;
  struct charac **curr_ptr ;
  int error ;

  {
  {
  curr_ptr = & curr;
  *curr_ptr = p1;

  error = GetKeyword(Keywords[88], curr_ptr);
  }
  if (error != 0) {
    return (1);
  }
  {
  error = angval(*curr_ptr, curr_ptr, unif_val_ptr, phase_unit_ptr);
  }






}
}



































































































































































































































#pragma merger("0","/tmp/cil-eHzDl9N5.i","")